### ISSUE TITLE
Interaction with Pawn addon causes repaint issues

### ISSUE THREAD

**Issue by mdebnam** [TheGeneticsGuy/Custom_Item_Notes#2]
Hi, love the addon. I've been looking for something to add notes to the random items in my bag for awhile.

Just a heads-up, in WoW Client v11.0.0.55960 and Pawn addon v2.9.14 there's a weird bug where the notes repaint repeatedly below the item tooltip. It looks to be some type of looping behavior as the text will flash repeatedly.

I've attached a screenshot. If I disable Pawn the behavior goes away.

![cin-pawn-interaction](https://github.com/user-attachments/assets/386dce80-3c7e-4f1d-8fae-9f784c08edca)

**Comment by TheGeneticsGuy** [comment]
Ah interesting. I'll look into it. Also, thanks for the reminder to update this addon. I just realized I've been focusing completely on my main addon "Guild Roster Manager" that I never even updated this for 11.0 release.

So, I'll get something out soon, it will probably be this weekend though when I have the time to work on it. I think there was something else someone requested I wanted to implement as well, a way to hide the note unless you pushed a hotkey down when hovering over it, which I liked, so I'll probably add that too as an option and add it to the addon options window. Anyway, thanks again for the report. Really appreciate it! I do not use the pawn addon so I would have never known. This will also help me adapt it to avoid future compatibility issues possibly with other addons too.

**Comment by TheGeneticsGuy** [comment]
Sorry for the long delay - the latest update this should now be resolved. Thanks!
