### ISSUE TITLE
[BUG] Spamming "MaybeID: xxxxx"

### ISSUE THREAD

**Issue by RabbleCode** [TheGeneticsGuy/Custom_Item_Notes#4]
In classic SoD, with release R1.19 the addon is spamming "MaybeID: xxxx" repeatedly in the chat frame when moused over an item tooltip.

Example: 
![image](https://github.com/user-attachments/assets/0806b58b-ea00-4fc8-a621-c66beea7de8a)

**Comment by RabbleCode** [comment]
Resolved locally by commenting out [line 183 in CIN_Core.lua](https://github.com/TheGeneticsGuy/Custom_Item_Notes/blob/361cc25e3991965ee216bc706720406cb1593375/CIN_Core.lua#L183). Looks like a debugging output snuck it's way in maybe?

**Comment by TheGeneticsGuy** [comment]
Oh crap, I left one of my test traces in this update. I'll push an update.

**Comment by TheGeneticsGuy** [comment]
Ok latest update has this fixed. Thanks for the report. Github hits me up right away thankfully. Curseforge never tells me when people comment except for a single email report at the end of the day, so it can literally be up to 24hrs since someone posted before I even know.

**Comment by RabbleCode** [comment]
Thank you! Installed R1.20 and verified it's resolved.

**Comment by TheGeneticsGuy** [comment]
You bet! I appreciate the swift reporting!
